[project]
name = "ex-conda"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
start = "ipython --config=$PIXI_PACKAGE_ROOT/conda_ipython.py"

[dependencies]
conda = "23.7.3.*"
ipython = "8.14.0.*"
